apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
    # ReadWriteMany  :- multiple nodes from multiple host can read and write not availble for host-pv
    # ReadOnlyMany   :- multiple nodes from multiple host can read not availble for host-pv
  hostPath:
    path: /data
    type: DirectoryOrCreate
