# stage 1 start
FROM node:14-alpine as build

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

# Stage 1 complete s instead of CMD use RUN
RUN npm run build          

# stage 2 starts
FROM nginx:stable-alpine

COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]



