version: "3.8"
services:
  urlshortener:
    build:
      context: ./app
      dockerfile: ${DOCKER_FILE}
    ports:
      - "8001:8080"
    volumes:
      - ./app:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - mongodb
